version: '3'

services:
  mysql:
    restart: always
    image: mysql:8.3
    container_name: main_server_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main_server
    ports:
      - "3308:3306"
    volumes:
      - ./db.cnf:/etc/mysql/conf.d/custom.cnf
      - ./tables.sql:/docker-entrypoint-initdb.d/0_tables.sql
      - ./users.sql:/docker-entrypoint-initdb.d/1_users.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2_data.sql