CREATE TABLE PRODUCT_CATEGORY
(
    ID_PRODUCT_CATEGORY INT AUTO_INCREMENT,
    NAME                VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_PRODUCT_CATEGORY),
    UNIQUE (NAME)
);

CREATE TABLE INVOICE
(
    ID_INVOICE  INT         AUTO_INCREMENT,
    PUBLISHING  DATETIME    NOT NULL,
    PRICE       DOUBLE      NOT NULL,
    PRIMARY KEY (ID_INVOICE)
);

CREATE TABLE PRODUCT
(
    REFERENCE           CHAR(6),
    NAME                VARCHAR(64) NOT NULL,
    PRICE               DOUBLE      NOT NULL,
    QUANTITY            SMALLINT    NOT NULL,
    ID_PRODUCT_CATEGORY INT         NOT NULL,
    PRIMARY KEY (REFERENCE),
    FOREIGN KEY (ID_PRODUCT_CATEGORY) REFERENCES PRODUCT_CATEGORY (ID_PRODUCT_CATEGORY)
);

CREATE TABLE INVOICE_PRODUCT
(
    ID_SHOPPING_CART    INT AUTO_INCREMENT,
    CHECKOUT_ID         SMALLINT    NOT NULL,
    QUANTITY            TINYINT     NOT NULL,
    ID_INVOICE          INT         NOT NULL,
    REFERENCE           CHAR(6)     NOT NULL,
    PRIMARY KEY (ID_SHOPPING_CART),
    FOREIGN KEY (ID_INVOICE) REFERENCES INVOICE (ID_INVOICE),
    FOREIGN KEY (REFERENCE) REFERENCES PRODUCT (REFERENCE)
);