CREATE TABLE PRODUCT_CATEGORY
(
    ID_PRODUCT_CATEGORY COUNTER,
    NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_PRODUCT_CATEGORY),
    UNIQUE (NAME)
);

CREATE TABLE INVOICE
(
    ID_INVOICE COUNTER,
    PUBLISHING DATETIME NOT NULL,
    PRICE      REAL     NOT NULL,
    PRIMARY KEY (ID_INVOICE)
);

CREATE TABLE PRODUCT
(
    REFERENCE           CHAR(6),
    NAME                VARCHAR(64) NOT NULL,
    PRICE               REAL        NOT NULL,
    QUANTITY            SMALLINT    NOT NULL,
    ID_PRODUCT_CATEGORY INT         NOT NULL,
    PRIMARY KEY (REFERENCE),
    FOREIGN KEY (ID_PRODUCT_CATEGORY) REFERENCES PRODUCT_CATEGORY (ID_PRODUCT_CATEGORY)
);

CREATE TABLE INVOICE_PRODUCT
(
    ID_SHOPPING_CART COUNTER,
    CHECKOUT_ID SMALLINT NOT NULL,
    QUANTITY BYTE NOT NULL,
    ID_INVOICE  INT      NOT NULL,
    REFERENCE   CHAR(6)  NOT NULL,
    PRIMARY KEY (ID_SHOPPING_CART),
    FOREIGN KEY (ID_INVOICE) REFERENCES INVOICE (ID_INVOICE),
    FOREIGN KEY (REFERENCE) REFERENCES PRODUCT (REFERENCE)
);
